spring:
  datasource:
    url: jdbc:mysql://192.168.3.15:3306/itsmboot-yzj-811
    username: root
    password: 123qweASD
    driver-class-name: com.mysql.cj.jdbc.Driver


datamigration:
  pagesize: 2000

mybatis-plus:
  mapper-locations: classpath:source/mapper/*.xml,classpath:target/mapper/*.xml