spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.15:3306/mysql_archiver?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowMultiQueries=true
    username: root
    password: 123qweASD
    max-active: 100

archive:
  pt-archiver-path: /opt/homebrew/bin
  archive-file-path: /opt/archive1
  batch-size: 2000
  txn-size: 100
  archive-user: root
  archive-pwd: 123qweASD

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml